name: package test

on: [push]

jobs:
  test:

    runs-on: macos-latest

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.7.0"
      - name: Get swift version
        run: swift --version
      - uses: actions/checkout@v3
      - name: Run tests
        run: swift test | xcpretty
